{
 "title": "Volume IO Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "show_mean", "label": "Hide Details", "query": "Yes, No" },
   {
    "name": "volume_id",
    "label": "Volume ID",
    "query": "label_values(powerflex_volume_read_bw,volume_id)"
   },
   {
    "name": "volume_name",
    "label": "Volume Name",
    "query": "label_values(powerflex_volume_read_bw,volume_name)"
   },
   {
    "name": "PVName",
    "label": "PV Name",
    "query": "label_values(powerflex_volume_read_bw,persistent_volume_name)"
   },
   { "name": "mapped_node_ids", "label": "Node IDs", "query": "label_values(id)" },
   { "name": "mapped_node_ips", "label": "Node IPs", "query": "label_values(ip)" },
   { "name": "TopX", "label": "Ranking", "query": "2,5,10,15,20,100,1000" },
   {
    "name": "TimeFrame",
    "label": "Average over Time",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Volume Read IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerflex_volume_read_iops{plot_with_mean=~\"($show_mean)\", volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",  mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"} and topk($TopX, avg_over_time(powerflex_volume_read_iops{plot_with_mean=~ \"($show_mean)\", volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",  mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"}[$TimeFrame]))",
     "legendFormat": "{{volume_name}}"
    },
    {
     "expr": "sum(powerflex_volume_read_iops{plot_with_mean=~\"($show_mean)|No\", volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",  mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"}) / count(powerflex_volume_read_iops{plot_with_mean=~\"($show_mean)|No\",volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"})",
     "legendFormat": "Average read_iops"
    }
   ]
  },
  {
   "title": "Volume Write IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerflex_volume_write_iops{plot_with_mean=~\"($show_mean)\", volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"} and topk($TopX, avg_over_time(powerflex_volume_write_iops{plot_with_mean=~\"($show_mean)\", volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"}[$TimeFrame]))",
     "legendFormat": "{{volume_name}}"
    },
    {
     "expr": "sum(powerflex_volume_write_iops{plot_with_mean=~\"($show_mean)|No\", volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",  mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"}) / count(powerflex_volume_write_iops{plot_with_mean=~\"($show_mean)|No\",volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"})",
     "legendFormat": "Average WriteIOP"
    }
   ]
  },
  {
   "title": "Volume Read Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerflex_volume_read_latency{plot_with_mean=~\"($show_mean)\", volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"} and topk($TopX, avg_over_time(powerflex_volume_read_latency{plot_with_mean=~\"($show_mean)\", volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"}[$TimeFrame]))",
     "legendFormat": "{{volume_name}}"
    },
    {
     "expr": "sum(powerflex_volume_read_latency{plot_with_mean=~\"($show_mean)|No\", volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",  mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"}) / count(powerflex_volume_read_latency{plot_with_mean=~\"($show_mean)|No\",volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"})",
     "legendFormat": "Average read_latency"
    }
   ]
  },
  {
   "title": "Volume Write Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerflex_volume_write_latency{plot_with_mean=~\"($show_mean)\", volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"} and topk($TopX, avg_over_time(powerflex_volume_write_latency{plot_with_mean=~\"($show_mean)\", volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"}[$TimeFrame]))",
     "legendFormat": "{{volume_name}}"
    },
    {
     "expr": "sum(powerflex_volume_write_latency{plot_with_mean=~\"($show_mean)|No\", volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",  mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"}) / count(powerflex_volume_write_latency{plot_with_mean=~\"($show_mean)|No\",volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"})",
     "legendFormat": "Average write_latency"
    }
   ]
  },
  {
   "title": "Volume Read Bandwidth (MB/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerflex_volume_read_bw{plot_with_mean=~\"($show_mean)\",volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"} and topk($TopX, avg_over_time(powerflex_volume_read_bw{plot_with_mean=~\"($show_mean)\",volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"}[$TimeFrame]))",
     "legendFormat": "{{volume_name}}"
    },
    {
     "expr": "sum(powerflex_volume_read_bw{plot_with_mean=~\"($show_mean)|No\", volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",  mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"}) / count(powerflex_volume_read_bw{plot_with_mean=~\"($show_mean)|No\",volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"})",
     "legendFormat": "Average read_bw"
    }
   ]
  },
  {
   "title": "Volume Write Bandwidth (MB/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerflex_volume_write_bw{plot_with_mean=~\"($show_mean)\", volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"} and topk($TopX, avg_over_time(powerflex_volume_write_bw{plot_with_mean=~\"($show_mean)\", volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"}[$TimeFrame]))",
     "legendFormat": "{{volume_name}}"
    },
    {
     "expr": "sum(powerflex_volume_write_bw{plot_with_mean=~\"($show_mean)|No\", volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",  mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"}) / count(powerflex_volume_write_bw{plot_with_mean=~\"($show_mean)|No\",volume_id=~\"$volume_id\",volume_name=~\"$volume_name\", persistent_volume_name=~\"$PVName\", mapped_node_ids=~\"(.*__)($mapped_node_ids)(__.*)\",mapped_node_ips=~\"(.*__)($mapped_node_ips)(__.*)\"})",
     "legendFormat": "Average write_bw"
    }
   ]
  }
 ]
}