/*
 Copyright (c) 2020-2022 Dell Inc. or its subsidiaries. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dell/karavi-metrics-powerflex/internal/service (interfaces: LeaderElector)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLeaderElector is a mock of LeaderElector interface.
type MockLeaderElector struct {
	ctrl     *gomock.Controller
	recorder *MockLeaderElectorMockRecorder
}

// MockLeaderElectorMockRecorder is the mock recorder for MockLeaderElector.
type MockLeaderElectorMockRecorder struct {
	mock *MockLeaderElector
}

// NewMockLeaderElector creates a new mock instance.
func NewMockLeaderElector(ctrl *gomock.Controller) *MockLeaderElector {
	mock := &MockLeaderElector{ctrl: ctrl}
	mock.recorder = &MockLeaderElectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeaderElector) EXPECT() *MockLeaderElectorMockRecorder {
	return m.recorder
}

// InitLeaderElection mocks base method.
func (m *MockLeaderElector) InitLeaderElection(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitLeaderElection", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitLeaderElection indicates an expected call of InitLeaderElection.
func (mr *MockLeaderElectorMockRecorder) InitLeaderElection(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitLeaderElection", reflect.TypeOf((*MockLeaderElector)(nil).InitLeaderElection), arg0, arg1)
}

// IsLeader mocks base method.
func (m *MockLeaderElector) IsLeader() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLeader")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsLeader indicates an expected call of IsLeader.
func (mr *MockLeaderElectorMockRecorder) IsLeader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLeader", reflect.TypeOf((*MockLeaderElector)(nil).IsLeader))
}
