// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dell/karavi-powerflex-metrics/internal/service (interfaces: PowerFlexSystem)

// Package mocks is a generated GoMock package.
package mocks

import (
	goscaleio "github.com/dell/goscaleio"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockPowerFlexSystem is a mock of PowerFlexSystem interface
type MockPowerFlexSystem struct {
	ctrl     *gomock.Controller
	recorder *MockPowerFlexSystemMockRecorder
}

// MockPowerFlexSystemMockRecorder is the mock recorder for MockPowerFlexSystem
type MockPowerFlexSystemMockRecorder struct {
	mock *MockPowerFlexSystem
}

// NewMockPowerFlexSystem creates a new mock instance
func NewMockPowerFlexSystem(ctrl *gomock.Controller) *MockPowerFlexSystem {
	mock := &MockPowerFlexSystem{ctrl: ctrl}
	mock.recorder = &MockPowerFlexSystemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPowerFlexSystem) EXPECT() *MockPowerFlexSystemMockRecorder {
	return m.recorder
}

// FindSdc mocks base method
func (m *MockPowerFlexSystem) FindSdc(arg0, arg1 string) (*goscaleio.Sdc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSdc", arg0, arg1)
	ret0, _ := ret[0].(*goscaleio.Sdc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSdc indicates an expected call of FindSdc
func (mr *MockPowerFlexSystemMockRecorder) FindSdc(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSdc", reflect.TypeOf((*MockPowerFlexSystem)(nil).FindSdc), arg0, arg1)
}
