// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dell/karavi-metrics-powerflex/internal/service (interfaces: StatisticsGetter)

// Package mocks is a generated GoMock package.
package mocks

import (
	goscaleio "github.com/dell/goscaleio"
	v1 "github.com/dell/goscaleio/types/v1"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockStatisticsGetter is a mock of StatisticsGetter interface
type MockStatisticsGetter struct {
	ctrl     *gomock.Controller
	recorder *MockStatisticsGetterMockRecorder
}

// MockStatisticsGetterMockRecorder is the mock recorder for MockStatisticsGetter
type MockStatisticsGetterMockRecorder struct {
	mock *MockStatisticsGetter
}

// NewMockStatisticsGetter creates a new mock instance
func NewMockStatisticsGetter(ctrl *gomock.Controller) *MockStatisticsGetter {
	mock := &MockStatisticsGetter{ctrl: ctrl}
	mock.recorder = &MockStatisticsGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStatisticsGetter) EXPECT() *MockStatisticsGetterMockRecorder {
	return m.recorder
}

// FindVolumes mocks base method
func (m *MockStatisticsGetter) FindVolumes() ([]*goscaleio.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindVolumes")
	ret0, _ := ret[0].([]*goscaleio.Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindVolumes indicates an expected call of FindVolumes
func (mr *MockStatisticsGetterMockRecorder) FindVolumes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindVolumes", reflect.TypeOf((*MockStatisticsGetter)(nil).FindVolumes))
}

// GetStatistics mocks base method
func (m *MockStatisticsGetter) GetStatistics() (*v1.SdcStatistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatistics")
	ret0, _ := ret[0].(*v1.SdcStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatistics indicates an expected call of GetStatistics
func (mr *MockStatisticsGetterMockRecorder) GetStatistics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatistics", reflect.TypeOf((*MockStatisticsGetter)(nil).GetStatistics))
}

// GetVolume mocks base method
func (m *MockStatisticsGetter) GetVolume() ([]*v1.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVolume")
	ret0, _ := ret[0].([]*v1.Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVolume indicates an expected call of GetVolume
func (mr *MockStatisticsGetterMockRecorder) GetVolume() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVolume", reflect.TypeOf((*MockStatisticsGetter)(nil).GetVolume))
}
