// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dell/karavi-metrics-powerflex/internal/service (interfaces: StoragePoolStatisticsGetter)
//
// Generated by this command:
//
//	mockgen -destination=mocks/storage_pool_statistics_getter_mocks.go -package=mocks github.com/dell/karavi-metrics-powerflex/internal/service StoragePoolStatisticsGetter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	v1 "github.com/dell/goscaleio/types/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockStoragePoolStatisticsGetter is a mock of StoragePoolStatisticsGetter interface.
type MockStoragePoolStatisticsGetter struct {
	ctrl     *gomock.Controller
	recorder *MockStoragePoolStatisticsGetterMockRecorder
	isgomock struct{}
}

// MockStoragePoolStatisticsGetterMockRecorder is the mock recorder for MockStoragePoolStatisticsGetter.
type MockStoragePoolStatisticsGetterMockRecorder struct {
	mock *MockStoragePoolStatisticsGetter
}

// NewMockStoragePoolStatisticsGetter creates a new mock instance.
func NewMockStoragePoolStatisticsGetter(ctrl *gomock.Controller) *MockStoragePoolStatisticsGetter {
	mock := &MockStoragePoolStatisticsGetter{ctrl: ctrl}
	mock.recorder = &MockStoragePoolStatisticsGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoragePoolStatisticsGetter) EXPECT() *MockStoragePoolStatisticsGetterMockRecorder {
	return m.recorder
}

// GetStatistics mocks base method.
func (m *MockStoragePoolStatisticsGetter) GetStatistics() (*v1.Statistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatistics")
	ret0, _ := ret[0].(*v1.Statistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatistics indicates an expected call of GetStatistics.
func (mr *MockStoragePoolStatisticsGetterMockRecorder) GetStatistics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatistics", reflect.TypeOf((*MockStoragePoolStatisticsGetter)(nil).GetStatistics))
}
