/*
 Copyright (c) 2020-2022 Dell Inc. or its subsidiaries. All Rights Reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
     http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dell/karavi-metrics-powerflex/internal/service (interfaces: StorageClassFinder)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/api/storage/v1"
)

// MockStorageClassFinder is a mock of StorageClassFinder interface.
type MockStorageClassFinder struct {
	ctrl     *gomock.Controller
	recorder *MockStorageClassFinderMockRecorder
}

// MockStorageClassFinderMockRecorder is the mock recorder for MockStorageClassFinder.
type MockStorageClassFinderMockRecorder struct {
	mock *MockStorageClassFinder
}

// NewMockStorageClassFinder creates a new mock instance.
func NewMockStorageClassFinder(ctrl *gomock.Controller) *MockStorageClassFinder {
	mock := &MockStorageClassFinder{ctrl: ctrl}
	mock.recorder = &MockStorageClassFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageClassFinder) EXPECT() *MockStorageClassFinderMockRecorder {
	return m.recorder
}

// GetStorageClasses mocks base method.
func (m *MockStorageClassFinder) GetStorageClasses() ([]v1.StorageClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorageClasses")
	ret0, _ := ret[0].([]v1.StorageClass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStorageClasses indicates an expected call of GetStorageClasses.
func (mr *MockStorageClassFinderMockRecorder) GetStorageClasses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorageClasses", reflect.TypeOf((*MockStorageClassFinder)(nil).GetStorageClasses))
}
