/*
 Copyright (c) 2020-2022 Dell Inc. or its subsidiaries. All Rights Reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
     http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dell/karavi-metrics-powerflex/internal/service (interfaces: StoragePoolStatisticsGetter)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	goscaleio "github.com/dell/goscaleio/types/v1"
	gomock "github.com/golang/mock/gomock"
)

// MockStoragePoolStatisticsGetter is a mock of StoragePoolStatisticsGetter interface.
type MockStoragePoolStatisticsGetter struct {
	ctrl     *gomock.Controller
	recorder *MockStoragePoolStatisticsGetterMockRecorder
}

// MockStoragePoolStatisticsGetterMockRecorder is the mock recorder for MockStoragePoolStatisticsGetter.
type MockStoragePoolStatisticsGetterMockRecorder struct {
	mock *MockStoragePoolStatisticsGetter
}

// NewMockStoragePoolStatisticsGetter creates a new mock instance.
func NewMockStoragePoolStatisticsGetter(ctrl *gomock.Controller) *MockStoragePoolStatisticsGetter {
	mock := &MockStoragePoolStatisticsGetter{ctrl: ctrl}
	mock.recorder = &MockStoragePoolStatisticsGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoragePoolStatisticsGetter) EXPECT() *MockStoragePoolStatisticsGetterMockRecorder {
	return m.recorder
}

// GetStatistics mocks base method.
func (m *MockStoragePoolStatisticsGetter) GetStatistics() (*goscaleio.Statistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatistics")
	ret0, _ := ret[0].(*goscaleio.Statistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatistics indicates an expected call of GetStatistics.
func (mr *MockStoragePoolStatisticsGetterMockRecorder) GetStatistics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatistics", reflect.TypeOf((*MockStoragePoolStatisticsGetter)(nil).GetStatistics))
}
