// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dell/karavi-metrics-powerflex/internal/service (interfaces: StorageClassFinder)
//
// Generated by this command:
//
//	mockgen -destination=mocks/storage_class_finder_mocks.go -package=mocks github.com/dell/karavi-metrics-powerflex/internal/service StorageClassFinder
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	k8s "github.com/dell/karavi-metrics-powerflex/internal/k8s"
	gomock "go.uber.org/mock/gomock"
)

// MockStorageClassFinder is a mock of StorageClassFinder interface.
type MockStorageClassFinder struct {
	ctrl     *gomock.Controller
	recorder *MockStorageClassFinderMockRecorder
	isgomock struct{}
}

// MockStorageClassFinderMockRecorder is the mock recorder for MockStorageClassFinder.
type MockStorageClassFinderMockRecorder struct {
	mock *MockStorageClassFinder
}

// NewMockStorageClassFinder creates a new mock instance.
func NewMockStorageClassFinder(ctrl *gomock.Controller) *MockStorageClassFinder {
	mock := &MockStorageClassFinder{ctrl: ctrl}
	mock.recorder = &MockStorageClassFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageClassFinder) EXPECT() *MockStorageClassFinderMockRecorder {
	return m.recorder
}

// GetStorageClasses mocks base method.
func (m *MockStorageClassFinder) GetStorageClasses() ([]k8s.StorageClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorageClasses")
	ret0, _ := ret[0].([]k8s.StorageClass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStorageClasses indicates an expected call of GetStorageClasses.
func (mr *MockStorageClassFinderMockRecorder) GetStorageClasses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorageClasses", reflect.TypeOf((*MockStorageClassFinder)(nil).GetStorageClasses))
}

// GetStoragePools mocks base method.
func (m *MockStorageClassFinder) GetStoragePools(storageClass k8s.StorageClass) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoragePools", storageClass)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetStoragePools indicates an expected call of GetStoragePools.
func (mr *MockStorageClassFinderMockRecorder) GetStoragePools(storageClass any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoragePools", reflect.TypeOf((*MockStorageClassFinder)(nil).GetStoragePools), storageClass)
}
