/*
 Copyright (c) 2020-2022 Dell Inc. or its subsidiaries. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dell/karavi-metrics-powerflex/internal/k8s (interfaces: NodeGetter)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockNodeGetter is a mock of NodeGetter interface.
type MockNodeGetter struct {
	ctrl     *gomock.Controller
	recorder *MockNodeGetterMockRecorder
}

// MockNodeGetterMockRecorder is the mock recorder for MockNodeGetter.
type MockNodeGetterMockRecorder struct {
	mock *MockNodeGetter
}

// NewMockNodeGetter creates a new mock instance.
func NewMockNodeGetter(ctrl *gomock.Controller) *MockNodeGetter {
	mock := &MockNodeGetter{ctrl: ctrl}
	mock.recorder = &MockNodeGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeGetter) EXPECT() *MockNodeGetterMockRecorder {
	return m.recorder
}

// GetNodes mocks base method.
func (m *MockNodeGetter) GetNodes() (*v1.NodeList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodes")
	ret0, _ := ret[0].(*v1.NodeList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodes indicates an expected call of GetNodes.
func (mr *MockNodeGetterMockRecorder) GetNodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodes", reflect.TypeOf((*MockNodeGetter)(nil).GetNodes))
}
